name: Bottle and Release

on: 
  push:
    branches:
      - main
    # tags:
    #    - "v*.*.*"

jobs:
  bottle:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platform: linux/arm64
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.bash_profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          sudo apt-get install build-essential
      -  
        name: Test Homebrew installation
        run: |
          brew --version
          brew --help
        # name: Build Homebrew bottle
        # run: |
        #   brew tap alan-turing-institute/hut23
        #   brew install --build-bottle --verbose alan-tuirng-institute/hut23/whatwhat
        #   brew bottle whatwhat
