name: Bottle and Release

on: 
  push:
    tags:
       - "v*.*.*"

jobs:
  bottle:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platform: linux/arm64
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build Homebrew bottle
        run: |
          brew tap alan-turing-institute/hut23
          brew install --build-bottle --verbose alan-tuirng-institute/hut23/whatwhat
          brew bottle whatwhat
