name: Build and publish documentation
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up OCaml 5.0.x
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.0.x
          dune-cache: false

      - name: Restore OPAM cache
        id: restore_opam_cache
        uses: actions/cache/restore@v3
        with:
          path: ~/.opam

      - name: Install dependencies and build
        # See: https://github.com/alan-turing-institute/whatwhat/wiki/Installing-dependencies
        run: |
          # Must do opam env, otherwise dune isn't in path.
          # 'opam exec -- dune' is an alternative
          eval $(opam env)
          opam install dune
          dune build || true
          opam install . --deps-only -y
          dune build

      - name: Build documentation (but not for dependencies)
        # See: https://github.com/alan-turing-institute/whatwhat/wiki/Documentation
        # Docs are placed in _build/default/_doc/_html
        run: |
          eval $(opam env)
          opam install odoc
          dune build @doc

      - name: Save OPAM cache (if it wasn't found)
        id: save_opam_cache
        if: steps.restore_opam_cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: ~/.opam

      - name: Clone gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Publish documentation
        run: |
          ls -R _build/default/_doc/_html
          rm -rf gh-pages/*
          cp -r _build/default/_doc/_html/* gh-pages
          cd gh-pages
          touch .nojekyll
          git config --local user.name "GitHub Actions"
          git config --local user.email "<hut23-1206-nowwhat@turing.ac.uk>"
          git add -A
          git commit -m "Update published documentation" || true
          git push
