# This Action updates the Homebrew tap (located at
# https://github.com/alan-turing-institute/homebrew-hut23) whenever a new
# version tag is pushed to this repository.

name: Bump Homebrew release

on:
  push:
    tags: "v*"

jobs:
  build_upload:
    name: Build whatwhat and upload executable for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # respectively: Linux, Intel Mac, M1 Mac
        os: [ubuntu-latest, macos-latest, macos-latest-xlarge]
    outputs:
      commit_sha: ${{ steps.get_sha.outputs.sha }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get SHA of latest commit
      id: get_sha
      run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Set up OCaml 5.0.x
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 5.0.x

    - name: Install dependencies and build
      run: |
        eval $(opam env)
        opam install dune
        dune build || true
        opam install . --deps-only -y
        dune build

    - name: Create tarball for upload (Linux)
      if: matrix.os == 'ubuntu-latest'
      run:
        tar cf whatwhat-${GITHUB_REF#refs/tags/v}-linux.tar.gz -C _build/default/bin main.exe
    - name: Create tarball for upload (Intel Mac)
      if: matrix.os == 'macos-latest'
      run:
        tar cf whatwhat-${GITHUB_REF#refs/tags/v}-macos.tar.gz -C _build/default/bin main.exe
    - name: Create tarball for upload (M1 Mac)
      if: matrix.os == 'macos-latest'
      run:
        tar cf whatwhat-${GITHUB_REF#refs/tags/v}-arm-macos.tar.gz -C _build/default/bin main.exe

    - name: Upload tarball
      id: upload_release_asset
      uses: softprops/action-gh-release@v1
      with:
        files: whatwhat*.tar.gz
